# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://kevin194.github.io',
                'git_url': 'https://github.com/kevin194/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.bar': ('core.html#bar', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.demo': {'nbdev_hello_world.demo.baz': ('demo.html#baz', 'nbdev_hello_world/demo.py')}}}
